version: '2'

services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 3306:3306
    volumes:
      - 'mariadb_data:/bitnami'

  testlink:
    image: 'bitnami/testlink:latest'
    labels:
      kompose.service.type: nodeport
    ports:
      - 80:80
      - 443:443
    volumes:
      - 'testlink_data:/bitnami'
    depends_on:
      - mariadb
  #  environment:
    # - TESTLINK_USERNAME=admin
     #- TESTLINK_PASSWORD=amin
     #- TESTLINK_EMAIL=admin@example.com

volumes:
  mariadb_data:
    driver: local
  testlink_data:
    driver: local
