version: '2'

services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_testlink
      - MARIADB_DATABASE=bitnami_testlink
    ports:
      - 3306:3306
    volumes:
      - 'mariadb_data:/bitnami'

  testlink:
    image: 'bitnami/testlink:latest'
    labels:
      kompose.service.type: nodeport
    ports:
      - 80:80
      - 443:443
    volumes:
      - 'testlink_data:/bitnami'
    depends_on:
      - mariadb
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - TESTLINK_DATABASE_USER=bn_testlink
      - TESTLINK_DATABASE_NAME=bitnami_testlink
      - ALLOW_EMPTY_PASSWORD=yes
      - TESTLINK_USERNAME=admin
      - TESTLINK_PASSWORD=admin
      - TESTLINK_EMAIL=admin@example.com

volumes:
  mariadb_data:
    driver: local
  testlink_data:
    driver: local
